language: node_js
node_js:
  - "6"
  - "7"
  - "8"
  - "node"

install:
  - npm install
  - npm install -g codecov istanbul
script:
  - npm run lint && npm run test
  - istanbul cover ./node_modules/.bin/mocha --reporter lcovonly -- -R spec
  - codecov

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
